server:
  port: 8010
spring:
  application:
    name: nacos-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#management.endpoints.web.exposure.include：暴露所有的 actuator 端点信息重启 服务，我们就可以在详情页面看到更多的数据。
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Sentinel 适配了 Feign 组件。但默认是关闭的。需要在配置文件中配置打开它，在配置文件增加以下代码：
feign:
  sentinel:
    enabled: true

